### ISSUE TITLE
bash tweaking

### ISSUE THREAD

**Issue by sph432** [qrp73/K5TOOL#1]
Your bash launcher won't work if not called from the same directory.

I suggest changing it to something along the lines of 
```bash
#!/usr/bin/env bash
mono "$(dirname ${BASH_SOURCE[0]:-$0})"/K5TOOL.exe "$@"
```
so that it will work as intended if added to $PATH.

**Comment by qrp73** [comment]
Thanks, fixed in https://github.com/qrp73/K5TOOL/commit/6d193904de2e1e9de43d79fcbe8aa02d89a08514
