### ISSUE TITLE
Read Firmware

### ISSUE THREAD

**Issue by vadimostanin** [qrp73/K5TOOL#2]
Backup of factory firmware is very important to rollback firmware, and to see difference between stock and custom firmwares.
It would be very helpful if your K5TOOL will support firmware's backup feature.

**Comment by qrp73** [comment]
Unfortunately, the bootloader don't have known command to read firmware.

You can find original firmware on manufacturer site: http://en.qsfj.com/products/3268 
Or here: https://github.com/ludwich66/Quansheng_UV-K5_Wiki/tree/main/firmware

**Comment by vadimostanin** [comment]
I see, Ok.
Thank you for feedback.
